### ISSUE TITLE
是否可以实现 https、http、socks5 都在同一端口提供服务呢

### ISSUE THREAD

**Issue by maxming2333** [ginuerzh/gost#1056]
我现在的配置，意思是启动一个 gost 程序，然后代理所有流量，然后 clash 可能启动也可以没启动，会自动做降级

这样就算我 clash 没启动，也可以正常走网卡直连

配置如下：
```yaml
services:
- name: service-0
  addr: ":7880"
  handler:
    type: auto
    chain: chain-0
  listener:
    type: tcp

chains:
- name: chain-0
  hops:
  - name: hop-0
    selector:
      strategy: round
      maxFails: 1
      failTimeout: 1s
    nodes:
    - name: node-0
      addr: :7890
      connector:
        type: socks5
      dialer:
        type: tcp
    - name: node-1
      addr: :0
      metadata:
        backup: true
      connector:
        type: virtual
      dialer:
        type: virtual
```

但是我现在需要一个 https 代理，因为终端某些程序必须要求 https 走 https 代理，不然就会报错
所以希望能一个端口实现 http、https、socks5 监听

目前我这种配置只是 http、socks5 在同一端口监听
