### ISSUE TITLE
请问怎么通过docker-compose.yml文件配置多链路转发

### ISSUE THREAD

**Issue by eicky** [ginuerzh/gost#571]
这是我的docker-compose.yml文件
```
version: "3"

services:
  redirect:
    container_name: gost
    image: ginuerzh/gost
    restart: always
    network_mode: "host"
    command:
      - "-L=tcp://:1111/1.1.1.1:1111"
      - "-L=tcp://:2222/2.2.2.2:2222"

      - "-L=tcp://3333/:3333"
      - "-F=ws://3.3.3.3:443"

      - "-L=tcp://:4444/4.4.4.4:4444"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

```
这是我在3.3.3.3服务器上运行的命令
```
./gost -L "ws://:443?path=/ws&rbuf=4096&wbuf=4096&compression=false"
```

发现一个问题，如果说3.3.3.3服务器出错了，那么其他的转发都会失效，不知道应该怎么去写这个docker-compose文件，让其支持多链路转发
