### ISSUE TITLE
黑名单可以屏蔽socks5,http,不能屏蔽https

### ISSUE THREAD

**Issue by bozai23** [ginuerzh/gost#802]
###  这是yaml格式配置文件，在代理QQ时，socks5可以屏蔽，http不可以屏蔽，请大佬指导
```
services:
- name: service-0
  addr: ":2323"
  handler:
     type: auto
     auth:
        username: bozai
        password: bozai
  listener:
     type: tcp
log:
  output: /opt/gost.log
  level: info
  format: json
bypasses:
- name: bypass-0
  reload: 10s
  reverse: false
  matchers:
  - myip.top
    '*.qq.com'
    '*.tencent.com'
    tcpconn2.tencent.com
```
