### ISSUE TITLE
Gost relay to brook

### ISSUE THREAD

**Issue by difof** [ginuerzh/gost#904]
Hello. I'm trying to check whether it's possible to use brook websocket behind gost's relay protocol for tunneling?

I followed the gost guides but gost give this error: 
`forward.go:136: [tcp] CLIENT_IP:43262 -> BROOK_IP:1122 : resolver: domain  does not exists`
I'm not using any domains, why is it trying to resolve domains?

Brook websockets command:
`$ brook wsserver -l 5.5.5.5:1122 -p mypass`

Gost relay command:
`$ gost -L udp://:1121 -L tcp://:1121 -F relay://5.5.5.5:1122`

[ [Brook Github](https://github.com/txthinking/brook/) ]

**Comment by uf1y** [comment]
You need a relay service running in brook server to talk with  relay client. You can’t relay data directly to wss port.
Server:
./gost -L ://:8888 -F tcp://127.0.0.1:1122
Client:
gost -L udp://:1121 -L tcp://:1121 -F relay://5.5.5.5:8888

**Comment by difof** [comment]
@uf1y It doesn't work, still gives the same error on gost client when I try to connect to brook

```yml
# docker-compose-brook-gost.yml
version: '3.8'
services:
  # MBWSS is just brook fork with config file support and Dockerfile
  mbwss:
    image: mbwss:latest
    command: ws -v -c /etc/mbwss.json
    networks:
      - app
    volumes:
      - ../../mbwss.json:/etc/mbwss.json

  gost-server:
    image: ginuerzh/gost
    command: -L relay://:8888 -F tcp://mbwss:${MBWSS_PORT}
    networks:
      - app
    depends_on:
      - mbwss

  gost-client:
    image: ginuerzh/gost
    command: -L udp://:${RELAY_PORT} -L tcp://:${RELAY_PORT} -F relay://gost-server:8888
    networks:
      - app
    ports:
      - "${RELAY_PORT}:${RELAY_PORT}"
    depends_on:
      - gost-server

networks:
  app:
```

**Comment by uf1y** [comment]
Try this to veryify your mbwss is working correctly, and then verify the relay solution.
```bash
./gost -L tcp://127.0.0.1:1122/5.5.5.5:1122
```

**Comment by difof** [comment]
mbwss through your last command is working and I could get some response, but relay verification says bad version from the gost relay server:

```
mbwss-mbwss-1        | HTTP server listening on 172.23.0.2:11223
mbwss-gost-server-1  | 2022/11/12 22:13:39 route.go:694: relay://:8888 on [::]:8888
mbwss-gost-test-1    | 2022/11/12 22:13:40 route.go:694: tcp://:11222 on [::]:11222
mbwss-gost-test-1    | 2022/11/12 22:13:42 forward.go:109: [tcp] 172.23.0.1:43318 - 172.23.0.4:11222
mbwss-gost-test-1    | 2022/11/12 22:13:42 forward.go:153: [tcp] 172.23.0.1:43318 <-> gost-server:8888
mbwss-gost-server-1  | 2022/11/12 22:13:42 relay.go:142: [relay] 172.23.0.4:36662 - 172.23.0.3:8888 : bad version        
mbwss-gost-test-1    | 2022/11/12 22:13:42 forward.go:155: [tcp] 172.23.0.1:43318 >-< gost-server:8888
```

Not sure what version it means though, both services use the same gost version.

I added this service to the compose file for the test and removed the gost-client service:
```yml
  gost-test:
    image: ginuerzh/gost
    command: -L tcp://:${RELAY_PORT}/gost-server:8888
    networks:
      - app
    ports:
      - "${RELAY_PORT}:${RELAY_PORT}"
    depends_on:
      - gost-server
```
