### ISSUE TITLE
https代理，提示unknown certificate

### ISSUE THREAD

**Issue by PHCSJC** [ginuerzh/gost#929]
服务端：gost -L=https://@:1080
客户端是chrome浏览器，用的SwitchyOmega，配置了https代理，但打不开网页，服务器端会提示未知证书，这个怎么办呢？
2023/02/10 11:26:46 http.go:99: [http]  : remote error: tls: unknown certificate
2023/02/10 11:26:46 http.go:99: [http]  : remote error: tls: unknown certificate
2023/02/10 11:26:47 http.go:99: [http]  : remote error: tls: unknown certificate

**Comment by ginuerzh** [comment]
你需要受信任的证书

**Comment by ding** [comment]
请教，使用了受信任的证书，使用acme脚本签发，下面是服务器配置，但是依然有类似的error，服务器端配置如下：
```
  - name: service-https
    addr: ":8338"
    handler:
      type: http2
      auth:
        username: uid
        password: pwd
      metadata:
        cert: /app/xxx.cer
        key: /app/xxx.key
        knock: www.google.com
        probeResistance: file:/var/www/html/index.html
    listener:
      type: http2
      metadata:
        cert: /app/xxx.cer
        key: /app/xxx.key
        knock: www.google.com
        probeResistance: file:/var/www/html/index.html
```

提示错误内容如下：
`gost[50898]: 2023/xx/xx 23:xx:xx http: TLS handshake error from xx.xx.xx.230:58844: remote error: tls: unknown certificate`

**Comment by ding** [comment]
@ginuerzh 能麻烦帮忙看下上面的问题么？

**Comment by ginuerzh** [comment]
v3版本中请参考https://gost.run/tutorials/tls/#_4

**Comment by lookcoins** [comment]
我也遇到同样的问题，请问解决了吗

**Comment by PHCSJC** [comment]
v3版本我试了，也是一样的错误，是不是必须得用域名？

**Comment by lookcoins** [comment]
域名我也试了，也一样

**Comment by royce2514** [comment]
caFile: ca.pem

把这个删掉。

**Comment by lookcoins** [comment]
> caFile: ca.pem
> 
> 把这个删掉。

不是很明白，只用key.pem吗

**Comment by lookcoins** [comment]
> remote error: tls: unknown certificate

服务器上还是提示remote error: tls: unknown certificate

**Comment by lookcoins** [comment]
> cert.pem和key.pem就行。你试试看
> 
> > > caFile: ca.pem
> > > 把这个删掉。
> > 
> > 
> > 不是很明白，只用key.pem吗

服务器上依然提示r
emote error: tls: unknown certificate

我试了用默认证书
试了用域名加上证书也是如此

**Comment by ginuerzh** [comment]
证书设置有误：
```
gost -L "http2://:8338?certFile=xxx.crt&keyFile=xxx.key"
```
或
```yaml
services:
  - name: service-0
    addr: :8338
    handler:
      type: http2
    listener:
      type: http2
      tls:
        certFile: xxx.crt
        keyFile: xxx.key
```
