### ISSUE TITLE
不支持网卡子接口

### ISSUE THREAD

**Issue by feeops** [ginuerzh/gost#945]
配置文件
```
services:
- name: service-0
  addr: ":8080"
  handler:
    type: auto
    chain: chain-0
  listener:
    type: tcp
chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      interface: eth0:0
      connector:
        type: virtual
      dialer:
        type: virtual
    - name: node-1
      interface: eth0:1
      connector:
        type: virtual
      dialer:
        type: virtual
```

结果输出
```
{"handler":"auto","kind":"service","level":"info","listener":"tcp","msg":"listening on [::]:8080/tcp","service":"service-0","time":"2023-03-17T20:40:22.750+08:00"}
{"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:8080","msg":"127.0.0.1:50638 <> 127.0.0.1:8080","remote":"127.0.0.1:50638","service":"service-0","time":"2023-03-17T20:40:28.212+08:00"}
{"handler":"auto","kind":"handler","level":"error","listener":"tcp","msg":"route(retry=0) route ip+net: no such network interface","service":"service-0","time":"2023-03-17T20:40:28.215+08:00"}
{"duration":2275169,"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:8080","msg":"127.0.0.1:50638 >< 127.0.0.1:8080","remote":"127.0.0.1:50638","service":"service-0","time":"2023-03-17T20:40:28.215+08:00"}
{"handler":"auto","kind":"service","level":"error","listener":"tcp","msg":"route ip+net: no such network interface","service":"service-0","time":"2023-03-17T20:40:28.215+08:00"}
^C{"handler":"auto","kind":"service","level":"error","listener":"tcp","msg":"accept: accept tcp [::]:8080: use of closed network connection","service":"service-0","time":"2023-03-17T20:40:41.939+08:00"}
```

版本号是
```
gost 3.0.0-rc.5 (go1.20 linux/amd64)
```
