### ISSUE TITLE
GOST failed to achieve intranet penetration using configuration files

### ISSUE THREAD

**Issue by ktpktr0** [ginuerzh/gost#992]
gost version: 2.11.5

Try using the following configuration file to achieve intranet penetration. One of my intranet services has multiple ports

Public network

```
services:
- name: service-0
  addr: ":13400"
  handler:
    type: socks5
    # 认证
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-1
  addr: ":13401"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-2
  addr: ":13402"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-3
  addr: ":13403"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-4
  addr: ":13404"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-5
  addr: ":13405"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-6
  addr: ":13406"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-7
  addr: ":13407"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-8
  addr: ":13408"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
- name: service-9
  addr: ":13409"
  handler:
    type: socks5
    auth:
      username: us
      password: Pass
  listener:
    type: ws
```

intranet

```
services:
  - name: service-0
    addr: :13400
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-0
        addr: 192.168.1.180:13400
  - name: service-1
    addr: :13401
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-1
        addr: 192.168.1.180:13401
  - name: service-2
    addr: :13402
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-2
        addr: 192.168.1.180:13402
  - name: service-3
    addr: :13403
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-3
        addr: 192.168.1.180:13403
  - name: service-4
    addr: :13404
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-4
        addr: 192.168.1.180:13404
  - name: service-5
    addr: :13405
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-5
        addr: 192.168.1.180:13405
  - name: service-6
    addr: :13406
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-6
        addr: 192.168.1.180:13406
  - name: service-7
    addr: :13407
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-7
        addr: 192.168.1.180:13407
  - name: service-8
    addr: :13408
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-8
        addr: 192.168.1.180:13408
  - name: service-9
    addr: :13409
    handler:
      type: rtcp
    listener:
      type: rtcp
      chain: chain-0
    forwarder:
      nodes:
      - name: target-9
        addr: 192.168.1.180:13409

chains:
  - name: chain-0
    hops:
    - name: hop-0
      nodes:
      - name: node-0
        addr: 10.10.10.10:13400
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-1
        addr: 10.10.10.10:13401
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-2
        addr: 10.10.10.10:13402
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-3
        addr: 10.10.10.10:13403
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-4
        addr: 10.10.10.10:13404
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-5
        addr: 10.10.10.10:13405
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-6
        addr: 10.10.10.10:13406
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-7
        addr: 10.10.10.10:13407
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-8
        addr: 10.10.10.10:13408
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
      - name: node-9
        addr: 10.10.10.10:13409
        connector:
          type: socks5
            auth:
            username: us
            password: Pass
        dialer:
          type: ws
```

When I try to run it, it won't work

# gost -C client.yml 
2023/11/05 16:51:17 main.go:53: invalid character 's' looking for beginning of value
# gost -C server.yml 
2023/11/05 16:51:21 main.go:53: invalid character 's' looking for beginning of value
